<div class="container py-4">
    <header>
        <h3 class="font-weight-bold text-dark text-center">
            <i class="fas fa-project-diagram pr-1"></i> DASHBOARD
        </h3>
    </header>

    <div class="card w-100 mt-3">
        <div id="product-card" class="div-img">
            <div class="text-card">
                <h2 class="font-weight-bold text-center mb-3"><?= $this->view->count_prod ?> PRODUTO(S)</h2>
                <a href="/product-consult" class="btn btn-primary btn-block w-75 mx-auto">Ver mais</a>
            </div>
        </div>
    </div>
    <?php if ($_SESSION['nivel_acesso'] == 2) : ?>
        <div class="card w-100 mt-3">
            <div id="employee-card" class="div-img">
                <div class="text-card">
                    <h2 class="font-weight-bold text-center mb-3"><?= $this->view->count_emp ?> FUNCIONÁRIOS(S)</h2>
                    <a href="/employee-consult" class="btn btn-primary btn-block w-75 mx-auto">Ver mais</a>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <div class="card w-100 mt-3">
        <div id="coach-card" class="div-img">
            <div class="text-card">
                <h2 class="font-weight-bold text-center mb-3"><?= $this->view->count_coach ?> TREINADORES(S)</h2>
                <a href="/coach-consult" class="btn btn-primary btn-block w-75 mx-auto">Ver mais</a>
            </div>
        </div>
    </div>
</div>