<div id="category" class="container py-4">
    <header>
        <h3 class="font-weight-bold text-dark"><i class="fas fa-certificate pr-1"></i> ESCOLHA OS PRODUTOS</h3>
    </header>

    <table class="table table-sm table-consult mt-1">
        <thead>
            <tr class="bg-danger">
                <th class="text-light">Produto</th>
                <th class="text-light">Valor</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>