<div id="category" class="container py-4">
    <header>
        <h3 class="font-weight-bold text-dark"><i class="fas fa-certificate pr-1"></i> ESCOLHA OS PRODUTOS</h3>
    </header>

    <div class="form-row">
        <div class="form-group col-11">
            <select name="products" id="products" class="form-control my-3">
                <option value="">Selecione um produto</option>
                <?php foreach ($this->view->list_prod as $prod) : ?>
                    <option value="<?= $prod['id_prod'] ?>" price="<?= $prod['preco'] ?>"><?= $prod['nome_prod'] ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group col-1">
            <button id="add" type="button" class="btn btn-primary btn-block mt-3 p-2"><i class="fas fa-plus"></i></button>
        </div>
    </div>
    <table class="table table-sm table-consult mt-1">
        <thead>
            <tr class="bg-danger">
                <th class="text-light">Produto</th>
                <th class="text-light">Valor</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>