<div id="category" class="container py-4">
    <header>
        <h3 class="font-weight-bold text-dark"><i class="fas fa-certificate pr-1"></i> ESCOLHA OS PRODUTOS</h3>
    </header>

    <form action="/category-consult" class="form-inline mt-5 form-search">
        <input class="form-control mr-sm-2" type="search" name="search" placeholder="Pesquisar" aria-label="Pesquisar">
        <button class="btn-search" type="submit">
            <i class="fas fa-search fa-lg"></i>
        </button>
    </form>

    <table class="table table-sm table-consult mt-1">
        <thead>
            <tr class="bg-danger">
                <th class="text-light">Produto</th>
                <th class="text-light">Valor</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>

    <div class="d-flex justify-content-center">
        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <h5 class="font-weight-bold">Treinador cadastrado?</h5>
                </div>
                <div class="card-body">
                    <select name="treinador" id="treinador" class="form-control">
                        <option value="">Selecione o treinador</option>
                        <option value="">Treinador 1</option>
                        <option value="">Treinador 2</option>
                        <option value="">Treinador 3</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <h5 class="font-weight-bold">Forma de pagamento</h5>
                </div>
                <div class="card-body">
                    <select name="forma-pagamento" id="forma-pagamento" class="form-control">
                        <option value="">Selecione a forma de pagamento</option>
                        <option value="">Dinheiro</option>
                        <option value="">Débito</option>
                        <option value="">Crédito</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <h5 class="font-weight-bold">Total</h5>
                </div>
                <div class="card-body">
                    <h4 class="text-center">$99.99</h4>
                </div>
            </div>
        </div>
    </div>

    <div class="toast-wrapper d-none">
        <div class="toast" role="alert">
            <div class="toast-header bg-success">
                <strong class="mr-auto">Sucesso</strong>
                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="toast-body">
                O registro foi excluído com sucesso
            </div>
        </div>
    </div>
</div>