<div id="category" class="container py-4">
    <header>
        <h3 class="font-weight-bold text-dark"><i class="fas fa-certificate pr-1"></i> ESCOLHA OS PRODUTOS</h3>
    </header>

    <div class="form-row">
        <div class="form-group col-11">
            <select name="products" id="products" class="form-control my-3">
                <option value="">Selecione um produto</option>
                <?php foreach ($this->view->list_prod as $prod) : ?>
                    <option value="<?= $prod['id_prod'] ?>" price="<?= $prod['preco'] ?>"><?= $prod['nome_prod'] ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group col-1">
            <button id="add" type="button" class="btn btn-primary btn-block mt-3 p-2"><i class="fas fa-plus"></i></button>
        </div>
    </div>

    <form action="">
        <table class="table table-sm table-consult mt-1">
            <thead>
                <tr class="bg-danger">
                    <th class="text-light">Produto</th>
                    <th class="text-light">Valor</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>

        <div class="row d-flex justify-content-center mt-5">
            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        <h5 class="font-weight-bold">Treinador cadastrado?</h5>
                    </div>
                    <div class="card-body">
                        <select name="treinador" id="treinador" class="form-control">
                            <option value="">Selecione o treinador</option>
                            <option value="">Treinador 1</option>
                            <option value="">Treinador 2</option>
                            <option value="">Treinador 3</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        <h5 class="font-weight-bold">Forma de pagamento</h5>
                    </div>
                    <div class="card-body">
                        <select name="forma-pagamento" id="forma-pagamento" class="form-control">
                            <option value="">Selecione a forma de pagamento</option>
                            <option value="">Dinheiro</option>
                            <option value="">Débito</option>
                            <option value="">Crédito</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        <h5 class="font-weight-bold">Total</h5>
                    </div>
                    <div class="card-body">
                        <h4 class="text-center">$<span id="total">0.00</span></h4>
                    </div>
                </div>
            </div>
        </div>

        <div class="row d-flex justify-content-center mt-4">
            <div class="col-6">
                <a href="/sale" class="btn btn-danger btn-block">Apagar</a>
            </div>
            <div class="col-6">
                <input type="submit" value="Finalizar" class="btn btn-success btn-block">
            </div>
        </div>
    </form>

    <div class="toast-wrapper d-none">
        <div class="toast" role="alert">
            <div class="toast-header bg-success">
                <strong class="mr-auto">Sucesso</strong>
                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="toast-body">
                O registro foi excluído com sucesso
            </div>
        </div>
    </div>
</div>