<div id="category" class="container py-4">
    <header>
        <h3 class="font-weight-bold text-dark"><i class="fas fa-certificate pr-1"></i> ESCOLHA OS PRODUTOS</h3>
    </header>

    <form action="/category-consult" class="form-inline mt-5 form-search">
        <input class="form-control mr-sm-2" type="search" name="search" placeholder="Pesquisar" aria-label="Pesquisar">
        <button class="btn-search" type="submit">
            <i class="fas fa-search fa-lg"></i>
        </button>
    </form>

    <table class="table table-sm table-consult mt-1">
        <thead>
            <tr class="bg-danger">
                <th class="text-light">Produto</th>
                <th class="text-light">Valor</th>
            </tr>
        </thead>
        <tbody>
            
        </tbody>
    </table>

    <div class="toast-wrapper d-none">
        <div class="toast" role="alert">
            <div class="toast-header bg-success">
                <strong class="mr-auto">Sucesso</strong>
                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="toast-body">
                O registro foi excluído com sucesso
            </div>
        </div>
    </div>
</div>