<div class="container py-4">
    <header>
        <h3 class="font-weight-bold text-dark"><i class="fas fa-certificate pr-1"></i> CONSULTAR CATEGORIA</h3>
        <a href="/category-create" class="btn btn-success btn-sm font-weight-bold mt-3">
            <i class="fas fa-plus"></i> NOVO REGISTRO
        </a>
    </header>

    <form class="form-inline mt-5 form-search">
        <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Pesquisar">
        <button class="btn-search" type="submit">
            <i class="fas fa-search fa-lg"></i>
        </button>
    </form>

    <div class="text-right">
        <small class="text-secondary">Há 52 registros</small>
    </div>

    <table class="table table-sm table-consult mt-1">
        <thead>
            <tr class="bg-danger">
                <th class="text-light">Nome</th>
                <th class="text-light"></th>
                <th class="text-light"></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->view->category_list as $categ) : ?>
                <tr>
                    <td><?= $categ['nome'] ?></td>
                    <td class="text-center text-info edit"><i class="fas fa-edit fa-lg"></i></td>
                    <td class="text-center text-danger delete"><i class="fas fa-trash fa-lg"></i></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>