<div class="container py-4">
    <header>
        <h3><i class="fas fa-certificate pr-1"></i> Consultar categoria</h3>
    </header>

    <table class="table table-sm mt-5">
        <thead>
            <tr class="bg-danger">
                <th class="text-light">Nome</th>
                <th class="text-light"></th>
                <th class="text-light"></th>
            </tr>
        </thead>
        <tbody>
            <tr class="row">
                <td class="col-8">Pokebola</td>
                <td class="col-2"><i class="fas fa-edit fa-lg"></i></td>
                <td class="col-2"><i class="fas fa-trash fa-lg"></i></td>
            </tr>
        </tbody>
    </table>
</div>