<div class="container py-4">
    <header>
        <h3><i class="fas fa-certificate pr-1"></i> Consultar categoria</h3>
        <a href="" class="btn btn-success btn-sm">NOVO REGISTRO</a>
    </header>

    <table class="table table-sm table-consult mt-5">
        <thead>
            <tr class="bg-danger">
                <th class="text-light">Nome</th>
                <th class="text-light"></th>
                <th class="text-light"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Pokebola</td>
                <td class="text-center text-info edit"><i class="fas fa-edit fa-lg"></i></td>
                <td class="text-center text-danger delete"><i class="fas fa-trash fa-lg"></i></td>
            </tr>
            <tr>
                <td>Antídotos</td>
                <td class="text-center text-info edit"><i class="fas fa-edit fa-lg"></i></td>
                <td class="text-center text-danger delete"><i class="fas fa-trash fa-lg"></i></td>
            </tr>
            <tr>
                <td>Gemas</td>
                <td class="text-center text-info edit"><i class="fas fa-edit fa-lg"></i></td>
                <td class="text-center text-danger delete"><i class="fas fa-trash fa-lg"></i></td>
            </tr>
        </tbody>
    </table>
</div>