<div class="container py-4">
    <header>
        <h3><i class="fas fa-certificate pr-1"></i> Consultar categoria</h3>
        <a href="" class="btn btn-success btn-sm font-weight-bold mt-3">
            <i class="fas fa-plus"></i> NOVO REGISTRO
        </a>
    </header>

    <form class="form-inline mt-5">
        <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Pesquisar">
        <button class="border-0" type="submit">
            <i class="fas fa-search fa-lg"></i>
        </button>
    </form>

    <table class="table table-sm table-consult mt-1">
        <thead>
            <tr class="bg-danger">
                <th class="text-light">Nome</th>
                <th class="text-light"></th>
                <th class="text-light"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Pokebola</td>
                <td class="text-center text-info edit"><i class="fas fa-edit fa-lg"></i></td>
                <td class="text-center text-danger delete"><i class="fas fa-trash fa-lg"></i></td>
            </tr>
            <tr>
                <td>Antídotos</td>
                <td class="text-center text-info edit"><i class="fas fa-edit fa-lg"></i></td>
                <td class="text-center text-danger delete"><i class="fas fa-trash fa-lg"></i></td>
            </tr>
            <tr>
                <td>Gemas</td>
                <td class="text-center text-info edit"><i class="fas fa-edit fa-lg"></i></td>
                <td class="text-center text-danger delete"><i class="fas fa-trash fa-lg"></i></td>
            </tr>
        </tbody>
    </table>
</div>