<div class="container py-4">
    <header>
        <h3 class="font-weight-bold text-dark"><i class="fas fa-certificate pr-1"></i> INSERIR CATEGORIA</h3>
        <a href="/category-consult" class="btn btn-info btn-sm font-weight-bold mt-3">
            <i class="fas fa-file-alt pr-1"></i> CONSULTAR
        </a>
    </header>

    <form id="create-category" action="/add-category" method="POST" class="mt-3">
        <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" id="nome" name="nome" class="form-control w-50">
        </div>
        <div class="form-group">
            <input type="submit" value="Gravar" class="btn btn-outline-success">
            <img id="ajax_load" src="/assets/imgs/load.gif" alt="Load gif" width="45" class="d-none">
        </div>
    </form>

    <div style="position: absolute; bottom: 0; right: 0;">
        <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
                <img src="..." class="rounded mr-2" alt="...">
                <strong class="mr-auto">Bootstrap</strong>
                <small class="text-muted">2 seconds ago</small>
                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="toast-body">
                Heads up, toasts will stack automatically
            </div>
        </div>
    </div>

</div>