<div class="container py-4">
    <header>
        <h3 class="font-weight-bold text-dark"><i class="fas fa-user pr-1"></i>  CONSULTAR TREINADORES</h3>
        <a href="/coach-create" class="btn btn-success btn-sm font-weight-bold mt-3">
            <i class="fas fa-plus"></i> NOVO REGISTRO
        </a>
    </header>

    <form class="form-inline mt-5 form-search">
        <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Pesquisar">
        <button class="btn-search" type="submit">
            <i class="fas fa-search fa-lg"></i>
        </button>
    </form>

    <div class="text-right">
        <small class="text-secondary">Há <b id="count_list"><?= count($this->view->category_list) ?></b> registro(s)</small>
    </div>

    <table class="table table-sm table-consult mt-1">
        <thead>
            <tr class="bg-danger">
                <th class="text-light">Nome</th>
                <th class="text-light">E-mail</th>
                <th class="text-light">Telefone</th>
                <th class="text-light">Data nascimento</th>
                <th class="text-light"></th>
                <th class="text-light"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Leonardo Alves</td>
                <td>leonardo.alves@gmail.com</td>
                <td>(11) 111111111</td>
                <td>04/06/2001</td>
                <td class="text-center text-info edit"><i class="fas fa-edit fa-lg"></i></td>
                <td class="text-center text-danger delete"><i class="fas fa-trash fa-lg"></i></td>
            </tr>
            <tr>
                <td>Ash Kutchen</td>
                <td>ash.kutchen@gmail.com</td>
                <td>(11) 222222222</td>
                <td>12/03/1986</td>
                <td class="text-center text-info edit"><i class="fas fa-edit fa-lg"></i></td>
                <td class="text-center text-danger delete"><i class="fas fa-trash fa-lg"></i></td>
            </tr>
            <tr>
                <td>Jessie James</td>
                <td>jessie.james@gmail.com</td>
                <td>(11) 333333333</td>
                <td>05/08/1999</td>
                <td class="text-center text-info edit"><i class="fas fa-edit fa-lg"></i></td>
                <td class="text-center text-danger delete"><i class="fas fa-trash fa-lg"></i></td>
            </tr>
        </tbody>
    </table>
</div>