<div class="container py-4">
    <header>
        <h3 class="font-weight-bold text-dark"><i class="fas fa-user pr-1"></i>  INSERIR TREINADOR</h3>
        <a href="/category-consult" class="btn btn-info btn-sm font-weight-bold mt-3">
            <i class="fas fa-file-alt pr-1"></i> CONSULTAR
        </a>
    </header>

    <form action="" class="mt-3">
        <div class="form-row">
            <div class="col-12 form-group">
                <label for="nome">Nome</label>
                <input type="text" id="nome" name="nome" class="form-control">
            </div>
            <div class="col-3 form-group">
                <label for="email">E-mail</label>
                <input type="email" id="email" name="email" class="form-control">
            </div>
            <div class="col-3 form-group">
                <label for="telefone">Telefone</label>
                <input type="text" id="telefone" name="telefone" class="form-control">
            </div>
            <div class="col-6 form-group">
                <label for="categoria">Categoria</label>
                <select name="categoria" id="categoria" class="form-control">
                    <option value="">Selecione uma categoria</option>
                    <option value="1">Pokeball</option>
                    <option value="2">Restauração de vida</option>
                    <option value="3">Potenciador de batalha</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Gravar" class="btn btn-outline-success">
        </div>
    </form>

</div>