<div class="container py-4">
    <header>
        <h3 class="font-weight-bold text-dark"><i class="fas fa-user pr-1"></i>  CONSULTAR TREINADORES</h3>
        <a href="/coach-create" class="btn btn-success btn-sm font-weight-bold mt-3">
            <i class="fas fa-plus"></i> NOVO REGISTRO
        </a>
    </header>

    <form class="form-inline mt-5 form-search">
        <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Pesquisar">
        <button class="btn-search" type="submit">
            <i class="fas fa-search fa-lg"></i>
        </button>
    </form>

    <div class="text-right">
        <small class="text-secondary">Há <b id="count_list"><?= count($this->view->coach_list) ?></b> registro(s)</small>
    </div>

    <table class="table table-sm table-consult mt-1">
        <thead>
            <tr class="bg-danger">
                <th class="text-light">Nome</th>
                <th class="text-light">E-mail</th>
                <th class="text-light">Telefone</th>
                <th class="text-light">Data nascimento</th>
                <th class="text-light"></th>
                <th class="text-light"></th>
            </tr>
        </thead>
        <tbody>
            <?php if (count($this->view->coach_list) >= 1) : ?>
                <?php foreach ($this->view->coach_list as $coach) : ?>
                    <?php

                    echo '<div class="modal fade" id="editModal' . $coach["id_treinador"] . '" tabindex="-1" role="dialog" aria-labelledby="editModal" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="editModalLabel">Editar treinador</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <form id="form_' . $coach["id_treinador"] . '" action="/edit-coach" method="POST">
                                        <div class="modal-body">
                                                <div class="form-group">
                                                    <label for="nome'. $coach["id_treinador"] .'" class="col-form-label">Nome</label>
                                                    <input type="text" class="form-control" id="nome'. $coach["id_treinador"] .'" name="nome" value="' . $coach["nome"] . '">
                                                </div>
                                                <div class="form-group">
                                                    <label for="email'. $coach["id_treinador"] .'" class="col-form-label">E-mail</label>
                                                    <input type="email" class="form-control" id="email'. $coach["id_treinador"] .'" name="email" value="' . $coach["email"] . '">
                                                </div>
                                                <div class="form-group">
                                                    <label for="telefone'. $coach["id_treinador"] .'" class="col-form-label">Telefone</label>
                                                    <input type="telefone" class="form-control" id="telefone'. $coach["id_treinador"] .'" name="telefone" value="' . $coach["telefone"] . '">
                                                </div>
                                                <div class="form-group">
                                                    <label for="data_nasc'. $coach["id_treinador"] .'" class="col-form-label">Data de nascimento</label>
                                                    <input type="date" class="form-control" id="data_nasc'. $coach["id_treinador"] .'" name="data_nasc" value="18/10/2022">
                                                </div>
                                                <input type="hidden" name="id" value="' . $coach["id_treinador"] . '">
                                            
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                            <button type="button" data-dismiss="modal" class="btn btn-primary" data-action="edit" data-id="' . $coach["id_treinador"] . '">Gravar</button>
                                            <img id="ajax_load" src="/assets/imgs/load.gif" alt="Load gif" width="45" class="d-none">
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>';

                    echo '<div class="modal fade" id="deleteModal' . $coach["id_treinador"] . '" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modalTitle">Tem certeza?</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Deseja realmente excluir este registro?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                    <button type="button" class="btn btn-danger" data-dismiss="modal" data-action="delete" data-id="' . $coach["id_treinador"] . '">Excluir</button>
                                </div>
                            </div>
                        </div>
                    </div>';


                    ?>
                    <tr id="line_<?= $coach['id_treinador'] ?>">
                        <td><?= $coach['nome'] ?></td>
                        <td><?= $coach['email'] ?></td>
                        <td><?= $coach['telefone'] ?></td>
                        <td><?= date_format(date_create($coach['data_nasc']), "d/m/Y") ?></td>
                        <td class="text-center text-info edit">
                            <i class="fas fa-edit fa-lg" data-toggle="modal" data-target="#editModal<?= $coach['id_treinador'] ?>" data-id="<?= $coach["id_treinador"] ?>"></i>
                        </td>
                        <td class="text-center text-danger delete">
                            <i class="fas fa-trash fa-lg" data-toggle="modal" data-target="#deleteModal<?= $coach['id_treinador'] ?>" data-id="<?= $coach["id_treinador"] ?>"></i>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else : ?>
                <tr class="text-danger">
                    <td>Nenhum registro encontrado</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>
</div>