<div class="container py-4">
    <header>
        <h3 class="font-weight-bold text-dark"><i class="fas fa-certificate pr-1"></i>  INSERIR TREINADOR</h3>
        <a href="/category-consult" class="btn btn-info btn-sm font-weight-bold mt-3">
            <i class="fas fa-file-alt pr-1"></i> CONSULTAR
        </a>
    </header>

    <form action="" class="mt-3">
        <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" id="nome" name="nome" class="form-control w-50">
        </div>
        <div class="form-group">
            <input type="submit" value="Gravar" class="btn btn-outline-success">
        </div>
    </form>

</div>