<div id="employee" class="container py-4">
    <header>
        <h3 class="font-weight-bold text-dark"><i class="fas fa-users pr-1"></i>  CONSULTAR FUNCIONÁRIO</h3>
        <a href="/employee-create" class="btn btn-success btn-sm font-weight-bold mt-3">
            <i class="fas fa-plus"></i> NOVO REGISTRO
        </a>
    </header>

    <form action="employee-consult" method="POST" class="form-inline mt-5 form-search">
        <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Pesquisar">
        <button class="btn-search" type="submit">
            <i class="fas fa-search fa-lg"></i>
        </button>
    </form>

    <div class="text-right">
        <small class="text-secondary">Há <b id="count_list"><?= count($this->view->emp_list) ?></b> registro(s)</small>
    </div>

    <table class="table table-sm table-consult mt-1">
        <thead>
            <tr class="bg-danger">
                <th class="text-light">Nome</th>
                <th class="text-light">Função</th>
                <th class="text-light text-center">Nível de Acesso</th>
                <th class="text-light"></th>
                <th class="text-light"></th>
            </tr>
        </thead>
        <tbody>
            <?php if (count($this->view->emp_list) >= 1) : ?>
                <?php foreach ($this->view->emp_list as $emp) : ?>
                    <?php

                    echo '<div class="modal fade" id="editModal' . $emp["id_func"] . '" tabindex="-1" role="dialog" aria-labelledby="editModal" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="editModalLabel">Editar funcionário</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <form id="form_' . $emp["id_func"] . '" action="/edit-employee" method="POST">
                                        <div class="modal-body">
                                                <div class="form-group">
                                                    <label for="nome'. $emp["id_func"] .'" class="col-form-label">Nome</label>
                                                    <input type="text" class="form-control" id="nome'. $emp["id_func"] .'" name="nome" value="' . $emp["nome"] . '">
                                                </div>
                                                <div class="form-group">
                                                    <label for="funcao'. $emp["id_func"] .'" class="col-form-label">Função</label>
                                                    <input type="text" class="form-control" id="funcao'. $emp["id_func"] .'" name="funcao" value="' . $emp["funcao"] . '">
                                                </div>
                                                <div class="form-group">
                                                    <label for="acesso'. $emp["id_func"] .'" class="col-form-label">Nível de acesso</label>
                                                    <select class="form-control" id="acesso'. $emp["id_func"] .'" name="acesso">';
                                                    $selected1 = "";
                                                    $selected2 = "";
                                                    $selected0 = "";
                                                    if($emp['nivel_acesso'] == 1) {
                                                        $selected1 = "selected";
                                                    }
                                                    elseif ($emp['nivel_acesso'] == 2) {
                                                        $selected2 = "selected";
                                                    }
                                                    else {
                                                        $selected0 = "selected";
                                                    }
                                                    echo "<option value='0' {$selected0}>0</option>
                                                        <option value='1' {$selected1}>1</option>
                                                        <option value='2' {$selected2}>2</option>";
                                                echo '</select>
                                                </div>
                                                <div class="form-group">
                                                    <label for="login'. $emp["id_func"] .'" class="col-form-label">Login</label>
                                                    <input type="text" class="form-control" id="login'. $emp["id_func"] .'" name="login" value="' . $emp["login"] . '">
                                                </div>
                                                <div class="form-group">
                                                    <label for="senha'. $emp["id_func"] .'" class="col-form-label">Senha</label>
                                                    <input type="text" class="form-control" id="senha'. $emp["id_func"] .'" name="senha" value="' . $emp["senha"] . '">
                                                </div>
                                                <input type="hidden" name="id" value="' . $emp["id_func"] . '">
                                            
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                            <button type="button" data-dismiss="modal" class="btn btn-primary" data-action="edit" data-id="' . $emp["id_func"] . '">Gravar</button>
                                            <img id="ajax_load" src="/assets/imgs/load.gif" alt="Load gif" width="45" class="d-none">
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>';

                    echo '<div class="modal fade" id="deleteModal' . $emp["id_func"] . '" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modalTitle">Tem certeza?</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Deseja realmente excluir este registro?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                    <button type="button" class="btn btn-danger" data-dismiss="modal" data-action="delete" data-id="' . $emp["id_func"] . '">Excluir</button>
                                </div>
                            </div>
                        </div>
                    </div>';


                    ?>
                    <tr id="line_<?= $emp['id_func'] ?>">
                        <td><?= $emp['nome'] ?></td>
                        <td><?= $emp['funcao'] ?></td>
                        <td class="text-center"><?= $emp['nivel_acesso'] ?></td>
                        <td class="text-center text-info edit">
                            <i class="fas fa-edit fa-lg" data-toggle="modal" data-target="#editModal<?= $emp['id_func'] ?>" data-id="<?= $emp["id_func"] ?>"></i>
                        </td>
                        <td class="text-center text-danger delete">
                            <i class="fas fa-trash fa-lg" data-toggle="modal" data-target="#deleteModal<?= $emp['id_func'] ?>" data-id="<?= $emp["id_func"] ?>"></i>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else : ?>
                <tr class="text-danger">
                    <td>Nenhum registro encontrado</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>

    <div class="toast-wrapper d-none">
        <div class="toast" role="alert">
            <div class="toast-header bg-success">
                <strong class="mr-auto">Sucesso</strong>
                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="toast-body">
                O registro foi excluído com sucesso
            </div>
        </div>
    </div>
</div>