<div class="container py-4">
    <header>
        <h3 class="font-weight-bold text-dark"><i class="fas fa-users pr-1"></i>  CONSULTAR FUNCIONÁRIO</h3>
        <a href="/employee-create" class="btn btn-success btn-sm font-weight-bold mt-3">
            <i class="fas fa-plus"></i> NOVO REGISTRO
        </a>
    </header>

    <form class="form-inline mt-5 form-search">
        <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Pesquisar">
        <button class="btn-search" type="submit">
            <i class="fas fa-search fa-lg"></i>
        </button>
    </form>

    <div class="text-right">
        <small class="text-secondary">Há <b id="count_list"><?= count($this->view->category_list) ?></b> registro(s)</small>
    </div>

    <table class="table table-sm table-consult mt-1">
        <thead>
            <tr class="bg-danger">
                <th class="text-light">Nome</th>
                <th class="text-light">Função</th>
                <th class="text-light">Nível de Acesso</th>
                <th class="text-light"></th>
                <th class="text-light"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Leonardo Alves</td>
                <td>Dono</td>
                <td>1</td>
                <td class="text-center text-info edit"><i class="fas fa-edit fa-lg"></i></td>
                <td class="text-center text-danger delete"><i class="fas fa-trash fa-lg"></i></td>
            </tr>
            <tr>
                <td>Chloe Moretz</td>
                <td>Médica</td>
                <td>3</td>
                <td class="text-center text-info edit"><i class="fas fa-edit fa-lg"></i></td>
                <td class="text-center text-danger delete"><i class="fas fa-trash fa-lg"></i></td>
            </tr>
            <tr>
                <td>Bruno Mars</td>
                <td>Faxineiro</td>
                <td>10</td>
                <td class="text-center text-info edit"><i class="fas fa-edit fa-lg"></i></td>
                <td class="text-center text-danger delete"><i class="fas fa-trash fa-lg"></i></td>
            </tr>
        </tbody>
    </table>
</div>