<div class="container py-4">
    <header>
        <h3 class="font-weight-bold text-dark text-center">
            <i class="fas fa-project-diagram pr-1"></i> DASHBOARD
        </h3>
    </header>

    <div class="card w-100">
        <div class="div-img">
        </div>
        <div class="card-body bg-white">
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
    </div>
</div>