<div class="container py-4">
    <header>
        <h3 class="font-weight-bold text-dark text-center">
            <i class="fas fa-project-diagram pr-1"></i> DASHBOARD
        </h3>
    </header>

    <div class="card w-100 mt-3">
        <div class="div-img">
            <div class="text-card">
                <h2 class="font-weight-bold text-center mb-3">52 PRODUTO(S)</h2>
                <a href="/product-consult" class="btn btn-primary btn-block w-75">Ver mais</a>
            </div>
        </div>
    </div>
</div>