<div class="container py-4">
    <header>
        <h3 class="font-weight-bold text-dark"><i class="fas fa-th-large pr-1"></i>  CONSULTAR PRODUTO</h3>
        <a href="/product-create" class="btn btn-success btn-sm font-weight-bold mt-3">
            <i class="fas fa-plus"></i> NOVO REGISTRO
        </a>
    </header>

    <form class="form-inline mt-5 form-search">
        <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Pesquisar">
        <button class="btn-search" type="submit">
            <i class="fas fa-search fa-lg"></i>
        </button>
    </form>

    <div class="text-right">
        <small class="text-secondary">Há <b id="count_list"><?= count($this->view->prod_list) ?></b> registro(s)</small>
    </div>

    <table class="table table-sm table-consult mt-1">
        <thead>
            <tr class="bg-danger">
                <th class="text-light">Nome</th>
                <th class="text-light">Preço</th>
                <th class="text-light">Estoque</th>
                <th class="text-light">Categoria</th>
                <th class="text-light"></th>
                <th class="text-light"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Master Ball</td>
                <td>$8.00</td>
                <td>85</td>
                <td>Pokebolas</td>
                <td class="text-center text-info edit"><i class="fas fa-edit fa-lg"></i></td>
                <td class="text-center text-danger delete"><i class="fas fa-trash fa-lg"></i></td>
            </tr>
            <tr>
                <td>Full Restore</td>
                <td>$14.00</td>
                <td>52</td>
                <td>Restauração de vida</td>
                <td class="text-center text-info edit"><i class="fas fa-edit fa-lg"></i></td>
                <td class="text-center text-danger delete"><i class="fas fa-trash fa-lg"></i></td>
            </tr>
            <tr>
                <td>Dire Hit</td>
                <td>$10.00</td>
                <td>59</td>
                <td>Potenciadores de batalha</td>
                <td class="text-center text-info edit"><i class="fas fa-edit fa-lg"></i></td>
                <td class="text-center text-danger delete"><i class="fas fa-trash fa-lg"></i></td>
            </tr>
        </tbody>
    </table>
</div>