<div class="container py-4">
    <header>
        <h3 class="font-weight-bold text-dark"><i class="fas fa-th-large pr-1"></i>  INSERIR PRODUTO</h3>
        <a href="/product-consult" class="btn btn-info btn-sm font-weight-bold mt-3">
            <i class="fas fa-file-alt pr-1"></i> CONSULTAR
        </a>
    </header>

    <form action="" class="mt-3">
        <div class="form-row">
            <div class="col-12 form-group">
                <label for="nome">Nome</label>
                <input type="text" id="nome" name="nome" class="form-control">
            </div>
            <div class="col-3 form-group">
                <label for="estoque">Estoque</label>
                <input type="text" id="estoque" name="estoque" class="form-control">
            </div>
            <div class="col-3 form-group">
                <label for="preco">Preço</label>
                <input type="text" id="preco" name="preco" class="form-control">
            </div>
            <div class="col-6 form-group">
                <select name="categoria" id="categoria">
                    <option value="">Selecione uma categoria</option>
                    <option value="1">Pokeball</option>
                    <option value="2">Restauração de vida</option>
                    <option value="3">Potenciador de batalha</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Gravar" class="btn btn-outline-success">
        </div>
    </form>

</div>