<div class="form-login">
    <form action="">
        <div class="d-flex justify-content-between mb-3">
            <hr class="flex-grow-1">
            <h5 class="flex-grow-1">BEM VINDO</h5>
            <hr class="flex-grow-1">
        </div>
        <div class="form-group">
            <label for="">Usuário: </label>
            <input type="text" name="username" class="form-control">
        </div>
        <div class="form-group">
            <label for="">Senha: </label>
            <input type="password" name="password" class="form-control">
        </div>
        <div class="form-group">
            <input type="submit" value="Entrar" class="btn btn-danger btn-block">
        </div>
    </form>
</div>