<html>
	<head>
		<meta charset="utf-8" />
		<title>Centro Pokémon</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

		<script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

		<link rel="stylesheet" type="text/css" href="/css/style.css">

	</head>

	<body>
        <div class="row d-flex justify-content-between px-4 py-2 info-bar">
            <div class="col-10 text-left">
                <h6>Bem-vindo ao sistema Centro Pokémon <?= $_SESSION['nome'] ?></h6>
            </div>
            <div class="col-2 text-right">
                <a href="/logout"><i class="fas fa-power-off fa-lg mt-2"></i></a>
            </div>
        </div>
        
        <div class="row d-flex justify-content-center">
            <aside class="col-2 pr-0 side-menu">
                <div class="px-3 pt-4 text-center">
                    <h5 class="font-weight-bold"><i class="fas fa-shopping-cart fa-lg"></i> Venda</h5>
                    <hr class="bg-secondary">
                </div>
                
                <ul>
                    <li>
                        <a href="/manager"><i class="fas fa-home pr-1"></i> Home</a>
                    </li>
                    <li>
                        <a href=""><i class="fas fa-home pr-1"></i> Histórico de vendas</a>
                    </li>
                </ul>

                <div class="p-3 button-back">
                    <a href="/dashboard" class="btn btn-outline-primary btn-block">
                        <i class="fas fa-arrow-alt-circle-left fa-lg pr-1"></i> Voltar
                    </a>
                </div>
            </aside>
            <div class="col-10">
                <?= $this->content() ?>
            </div>
        </div>

        <script src="/js/script.js"></script>
	</body>

</html>