<html>
	<head>
		<meta charset="utf-8" />
		<title>Centro Pokémon</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

		<link rel="stylesheet" type="text/css" href="/css/style.css">

	</head>

	<body>
        <div class="row d-flex justify-content-between px-4 py-2 info-bar">
            <div class="col-10 text-left">
                <h6>Bem-vindo ao sistema Centro Pokémon <?= $_SESSION['nome'] ?></h6>
            </div>
            <div class="col-2 text-right">
                <a href="/logout"><i class="fas fa-power-off fa-lg mt-2"></i></a>
            </div>
        </div>
        
        <div class="row d-flex justify-content-center">
            <aside class="col-2 pr-0 side-menu">
                <div class="px-3 pt-4 text-center">
                    <h5 class="font-weight-bold"><i class="fas fa-cogs fa-lg"></i> Gerenciamento</h5>
                    <hr class="bg-secondary">
                </div>
                
                <ul>
                    <li>
                        <a href="/manager"><i class="fas fa-home pr-1"></i> Home</a>
                    </li>
                    <li>
                        <a href="#"><i class="fas fa-cog pr-1"></i> Setup</a>
                    </li>
                    <li>
                        <a href="#product" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapse">
                            <i class="fas fa-th-large pr-1"></i> Produto
                        </a>
                        <ul class="collapse" id="product">
                            <li>
                                <a href="/product-consult">Consultar produtos</a>
                            </li>
                            <li>
                                <a href="/product-create">Inserir novo produto</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#category" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapse">
                            <i class="fas fa-certificate pr-1"></i> Categoria
                        </a>
                        <ul class="collapse" id="category">
                            <li>
                                <a href="/category-consult">Consultar categorias</a>
                            </li>
                            <li>
                                <a href="/category-create">Inserir nova categoria</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#employee" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapse">
                            <i class="fas fa-users pr-1"></i> Funcionário
                        </a>
                        <ul class="collapse" id="employee">
                            <li>
                                <a href="/employee-consult">Consultar funcionários</a>
                            </li>
                            <li>
                                <a href="/employee-create">Inserir novo funcionário</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#coach" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapse">
                            <i class="fas fa-user pr-1"></i> Treinador
                        </a>
                        <ul class="collapse" id="coach">
                            <li>
                                <a href="/coach-consult">Consultar treinadores</a>
                            </li>
                            <li>
                                <a href="/coach-create">Inserir novo treinador</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </aside>
            <div class="col-10">
                <?= $this->content() ?>
            </div>
        </div>
	</body>

</html>