<div class="row d-flex justify-content-center w-75 mx-auto center-x-y">
    <div class="col-4">
        <a href="" class="card-dashboard">
            <i class="fas fa-shopping-cart fa-4x"></i>
            <h4>VENDAS</h4>
        </a>
    </div>
    <div class="col-4">
        <a href="" class="card-dashboard">
            <i class="fas fa-shopping-cart fa-4x"></i>
            <h4>ATENDIMENTO</h4>
        </a>
    </div>
    <div class="col-4">
        <a href="" class="card-dashboard">
            <i class="fas fa-shopping-cart fa-4x"></i>
            <h4>GERENCIAMENTO</h4>
        </a>
    </div>
</div>