<div class="row d-flex justify-content-center">
    <aside class="col-2 pr-0 side-menu">
        <div class="px-3 pt-4 text-center">
            <h5 class="font-weight-bold"><i class="fas fa-cogs fa-lg"></i> Gerenciamento</h5>
            <hr class="bg-secondary">
        </div>
        
        <ul>
            <li>
                <a href="#product" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapse">
                    <i class="fas fa-th-large"></i> Produto
                </a>
                <ul class="collapse" id="product">
                    <li>
                        <a href="">Consultar produtos</a>
                    </li>
                    <li>
                        <a href="">Inserir novo produto</a>
                    </li>
                </ul>
            </li>
        </ul>
    </aside>
    <div class="col-10">
        <h2>Teste</h2>
    </div>
</div>